name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Download dependencies
      run: |
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/boost-1.75.0.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/flac-1.3.3.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/oboe-1.5.0.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/ogg-1.3.4.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/opus-1.1.2.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/soxr-0.1.3.aar -P Snapcast/libs/
        wget https://github.com/badaix/snapcast-deps/releases/download/v0.24.0/tremor-1.0.0.aar -P Snapcast/libs/
    - name: Build the app
      run: ./gradlew build

    - name: rename apk
      run: mv /home/runner/work/snapdroid/snapdroid/Snapcast/build/outputs/apk/release/Snapcast-release-unsigned.apk /home/runner/work/snapdroid/snapdroid/Snapcast/build/outputs/apk/release/Snapcast.apk 

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: /home/runner/work/snapdroid/snapdroid/Snapcast/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: develop_snapshot-${{github.sha}}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
